FROM php:7.2-apache

#
# PHP Configuration
#
# install PHP modules
# ----------
RUN apt-get update -qq\
    && apt-get install -y --no-install-recommends \
          zlib1g-dev \
          wget \
          unzip \
          sudo \
          git \
          imagemagick \
          perlmagick \
          libdbi-perl \
          libdbd-mysql-perl \
          libcache-memcached-perl \
          libgd-perl \
          libimager-perl \
          libipc-run-perl \
          libarchive-zip-perl \
          libxml-atom-perl \
          libxml-sax-expatxs-perl \
          libyaml-syck-perl \
    && docker-php-ext-install zip \
    && docker-php-ext-install pdo_mysql


# install GD
# ----------
RUN apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install gd


# install Imagemagick & PHP Imagick ext
# ----------
RUN apt-get install -y \
        libmagickwand-dev --no-install-recommends \
    && pecl install imagick \
    && docker-php-ext-enable imagick


# cleanup
# ----------
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# enable cgi / mod_rewite
# ----------
RUN a2enmod cgi
RUN a2enmod rewrite


# install composer
# ----------
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
