version: '3'

services:
  db:
    container_name: ${CONTAINER_BASE_NAME}-db
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ${DB_PATH}:/var/lib/mysql
      - ./docker/config/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${HOST_MYSQL_PORT}:3306

  apache:
    container_name: ${CONTAINER_BASE_NAME}-apache
    build: ./docker/apache/
    restart: unless-stopped
    volumes:
      - ${APACHE_BASE_PATH}:/var/www/html
      - ${CMS_BASE_PATH}:/data/mt
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/user-php.ini
      - ./docker/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      # CERT_NAME: ${CERT_NAME}
      # HTTPS_METHOD: ${HTTPS_METHOD}
    depends_on:
      - db

networks:
    default:
       external:
         name: ${NETWORK}
