version: '3'

services:
  db:
    container_name: ${CONTAINER_BASE_NAME}-db
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ${DB_PATH}:/var/lib/mysql:delegated
      - ./docker/config/my.cnf:/etc/mysql/mysql.conf.d/my.cnf:cached
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${HOST_MYSQL_PORT}:3306

  apache:
    container_name: ${CONTAINER_BASE_NAME}-apache
    build: ./docker/apache/
    restart: unless-stopped
    volumes:
      - ${APACHE_BASE_PATH}:/var/www/html:delegated
      - ${CMS_BASE_PATH}:/data/mt:delegated
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/user-php.ini:cached
      - ./docker/config/000-default.conf:/etc/apache2/sites-available/000-default.conf:cached
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      # CERT_NAME: ${CERT_NAME}
      # HTTPS_METHOD: ${HTTPS_METHOD}
    depends_on:
      - db
    # ports:
    #   - ${HOST_HTTP_PORT}:80

networks:
  default:
    external: true
    name: ${NETWORK}
